### ISSUE TITLE
Running `xs-dev setup` fails due to a missing `lin` import

### ISSUE THREAD

**Issue by dahenson** [HipsterBrown/xs-dev#189]
I am unable to run `xs-dev setup` on Fedora 40. It appears that the host device is detected as `lin`, which is then required from `toolbox/setup/lin`, but the file doesn't exist.

## Steps taken
- Install `xs-dev` on Fedora with `pnpm install --global xs-dev`
- Run `xs-dev setup`
Output:
```
Command failed, Error: Cannot find module '../toolbox/setup/lin'
Require stack:
- /home/redacted/.local/share/pnpm/global/5/.pnpm/xs-dev@0.33.1/node_modules/xs-dev/build/src/commands/setup.js
- /home/redacted/.local/share/pnpm/global/5/.pnpm/xs-dev@0.33.1/node_modules/xs-dev/build/src/cli.js
    at Function._resolveFilename (node:internal/modules/cjs/loader:1239:15)
    at Function._load (node:internal/modules/cjs/loader:1064:27)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
    at Module.require (node:internal/modules/cjs/loader:1325:12)
    at require (node:internal/modules/helpers:136:16)
    at /home/redacted/.local/share/pnpm/global/5/.pnpm/xs-dev@0.33.1/node_modules/xs-dev/build/src/commands/setup.js:85:116
    at async Object.func (/home/redacted/.local/share/pnpm/global/5/.pnpm/xs-dev@0.33.1/node_modules/xs-dev/build/src/commands/setup.js:85:36)
    at async Fe (/home/redacted/.local/share/pnpm/global/5/.pnpm/@stricli+core@1.1.0/node_modules/@stricli/core/dist/index.cjs:7:33)
    at async pn (/home/redacted/.local/share/pnpm/global/5/.pnpm/@stricli+core@1.1.0/node_modules/@stricli/core/dist/index.cjs:23:672)
```

## Environment
Operating system: Fedora 40
Node version: v23.3.0 (installed via asdf)
pnpm version: 9.14.2

**Comment by dahenson** [comment]
I was able to reproduce this issue in Ubuntu 22.04. I have submitted a fix that should work for most distros, but more improvements will need to be made in order to allow `xs-dev setup` to be run on any linux machine.
